version: 2.1

references:
  workdir: &workdir
    working_directory: ~/source

  persist-workspace: &persist-workspace
    persist_to_workspace:
      root: ~/source
      paths:
        - .

  attach-workspace: &attach-workspace
    attach_workspace:
      at: .

commands:
  run_maven:
    description:
    parameters:
        branch_to_deploy:
          type: string
          default: "master"
    steps:
      # Built module is stored in: /home/circleci/source/repo/repo/api/target/jcontent-2.0.0-SNAPSHOT.jar
      - run:
          name: Maven call
          command: |
            if [[ "${CIRCLE_BRANCH}" == "<< parameters.branch_to_deploy >>" ]];
            then
              mvn -s .circleci/.circleci.settings.xml clean install deploy
            else
              mvn -s .circleci/.circleci.settings.xml clean install
            fi

jobs:
  install:
    <<: *workdir

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
   
    resource_class: large

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run_maven
      - save_cache:
          paths:
            - ~/.m2
          key: v2-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Prepare artifacts
          command: |
            mkdir /tmp/artifacts/
            cp /home/circleci/source/target/*.jar /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts/
      - *persist-workspace

workflows:
  version: 2
  build:
    jobs:
      - install:
          context: QA_ENVIRONMENT
